version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "tg_bating1"
      POSTGRES_USER: "user1"
      POSTGRES_PASSWORD: "123123"
    ports:
      - "5439:5432"